#google Oauth2 credentials
spring.security.oauth2.client.registration.google.client-id=32475229386-knvo8holf2oe068igegmapj8s2s3hcjf.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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



#github Oauth2 credentials
spring.security.oauth2.client.registration.github.client-id=Ov23li1zzVH3vX39XxyZ
spring.security.oauth2.client.registration.github.client-secret=6ab34cfbd43d687b0e4442e2cb37e548966ca0d4
